//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common_proto.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3Proto")]
  public partial class Vector3Proto : global::ProtoBuf.IExtensible
  {
    public Vector3Proto() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEventProto")]
  public partial class GameEventProto : global::ProtoBuf.IExtensible
  {
    public GameEventProto() {}
    
    private int _eventType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private int _triggerTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"triggerTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int triggerTime
    {
      get { return _triggerTime; }
      set { _triggerTime = value; }
    }
    private ProtoBuf.EffectProto _effectData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"effectData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.EffectProto effectData
    {
      get { return _effectData; }
      set { _effectData = value; }
    }
    private ProtoBuf.SoundProto _soundData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"soundData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.SoundProto soundData
    {
      get { return _soundData; }
      set { _soundData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectProto")]
  public partial class EffectProto : global::ProtoBuf.IExtensible
  {
    public EffectProto() {}
    
    private ProtoBuf.Vector3Proto _offset = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3Proto offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private ProtoBuf.Vector3Proto _rotate = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rotate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3Proto rotate
    {
      get { return _rotate; }
      set { _rotate = value; }
    }
    private float _scale = (float)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private string _assetName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"assetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assetName
    {
      get { return _assetName; }
      set { _assetName = value; }
    }
    private string _bindBone = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bindBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bindBone
    {
      get { return _bindBone; }
      set { _bindBone = value; }
    }
    private int _bindMode = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bindMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bindMode
    {
      get { return _bindMode; }
      set { _bindMode = value; }
    }
    private int _deleteMode = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"deleteMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deleteMode
    {
      get { return _deleteMode; }
      set { _deleteMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoundProto")]
  public partial class SoundProto : global::ProtoBuf.IExtensible
  {
    public SoundProto() {}
    
    private string _assetName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"assetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assetName
    {
      get { return _assetName; }
      set { _assetName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}