//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common_proto.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3Proto")]
  public partial class Vector3Proto : global::ProtoBuf.IExtensible
  {
    public Vector3Proto() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectProto")]
  public partial class EffectProto : global::ProtoBuf.IExtensible
  {
    public EffectProto() {}
    
    private ProtoBuf.Vector3Proto _offset = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3Proto offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private ProtoBuf.Vector3Proto _rotate = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rotate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3Proto rotate
    {
      get { return _rotate; }
      set { _rotate = value; }
    }
    private ProtoBuf.Vector3Proto _scale = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.Vector3Proto scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private float _triggerTime = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"triggerTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float triggerTime
    {
      get { return _triggerTime; }
      set { _triggerTime = value; }
    }
    private string _assetName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"assetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assetName
    {
      get { return _assetName; }
      set { _assetName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoundProto")]
  public partial class SoundProto : global::ProtoBuf.IExtensible
  {
    public SoundProto() {}
    
    private string _assetName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"assetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assetName
    {
      get { return _assetName; }
      set { _assetName = value; }
    }
    private float _triggerTime = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"triggerTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float triggerTime
    {
      get { return _triggerTime; }
      set { _triggerTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}