//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: packer_proto.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PatchableIndexInfo")]
  public partial class PatchableIndexInfo : global::ProtoBuf.IExtensible
  {
    public PatchableIndexInfo() {}
    
    private int _CRCID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CRCID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CRCID
    {
      get { return _CRCID; }
      set { _CRCID = value; }
    }
    private string _AssetName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AssetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AssetName
    {
      get { return _AssetName; }
      set { _AssetName = value; }
    }
    private int _RootPathType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"RootPathType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RootPathType
    {
      get { return _RootPathType; }
      set { _RootPathType = value; }
    }
    private int _MatchCRC = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MatchCRC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MatchCRC
    {
      get { return _MatchCRC; }
      set { _MatchCRC = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PatchableIndexSetupInfo")]
  public partial class PatchableIndexSetupInfo : global::ProtoBuf.IExtensible
  {
    public PatchableIndexSetupInfo() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.PatchableIndexInfo> _Datas = new global::System.Collections.Generic.List<ProtoBuf.PatchableIndexInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.PatchableIndexInfo> Datas
    {
      get { return _Datas; }
    }
  
    private string _SystemTimeDate = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SystemTimeDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SystemTimeDate
    {
      get { return _SystemTimeDate; }
      set { _SystemTimeDate = value; }
    }
    private int _Version = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompressFileInfo")]
  public partial class CompressFileInfo : global::ProtoBuf.IExtensible
  {
    public CompressFileInfo() {}
    
    private string _AssetName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AssetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AssetName
    {
      get { return _AssetName; }
      set { _AssetName = value; }
    }
    private byte[] _Bytes = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Bytes
    {
      get { return _Bytes; }
      set { _Bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompressPackageInfo")]
  public partial class CompressPackageInfo : global::ProtoBuf.IExtensible
  {
    public CompressPackageInfo() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.CompressFileInfo> _FileList = new global::System.Collections.Generic.List<ProtoBuf.CompressFileInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"FileList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CompressFileInfo> FileList
    {
      get { return _FileList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}