// Generated by the Table Description Language compiler.  DO NOT EDIT!
// source: skill_table.prot

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


public class SkillTable : Table.Binary, Table.IKey
{
	UInt32       m_baseid;
	Table.String m_name;
	Table.String m_describtion;
	UInt16       m_lv_unlock;
	Byte         m_type;
	Byte         m_power_requst;
	
	public const UInt32 Version = 4248846321;
	
	public UInt64 Key()
	{
		return m_baseid;
	}
	
	public UInt32 baseid
	{
		get { return m_baseid; }
	}
	
	public string name
	{
		get { return m_name; }
	}
	
	public string describtion
	{
		get { return m_describtion; }
	}
	
	public UInt16 lvUnlock
	{
		get { return m_lv_unlock; }
	}
	
	public Byte type
	{
		get { return m_type; }
	}
	
	public Byte powerRequst
	{
		get { return m_power_requst; }
	}
	
	public override int Load(byte[] buffer, int index)
	{
		Table.Loader loader = new Table.Loader(ref buffer, index);
		loader.Load(ref m_baseid).Load(ref m_name).Load(ref m_describtion).Load(ref m_lv_unlock).Load(ref m_type).Load(ref m_power_requst);
		return loader.Size;
	}
}

// source: skill_table.xls, sheet: Sheet1
public sealed class SkillTableManager : Table.Manager<SkillTable>
{
	private static readonly SkillTableManager ms_instance = new SkillTableManager();
	
	private SkillTableManager()
	{
	}
	
	public static SkillTableManager instance
	{
		get { return ms_instance; }
	}
	
	public string source
	{
		get { return "skill_table.tbl"; }
	}
	
	public bool Load(string path)
	{
		Register();
		return Load(path, source, SkillTable.Version);
	}
	
	public SkillTable Find(UInt32 key)
	{
		return FindInternal(key);
	}
	
	#region new helper
	public static object NewSkillTable()
	{
		return new SkillTable();
	}
	
	private static void Register()
	{
		Table.NewHelper.Clear();
		Table.NewHelper.Register(typeof(SkillTable), NewSkillTable);
	}
	#endregion
}

